### ISSUE TITLE
PhnxSnippets package is ALIVE doesn't disappear

### ISSUE THREAD

**Issue by krrishh-org** [vivekdtiwari/phnx-snippets#1]
Steps to reproduce:

- Open command pallette (Ctrl+Shift+P) 
- Search for 'Phnx Snippets: Toggle'
- Hit Enter

or 

just press 'Ctrl + Alt + O'

Result:
![screenshot from 2017-05-14 12-04-06](https://cloud.githubusercontent.com/assets/19912501/26031784/fbe6e1b8-389d-11e7-91d6-d7cbd55144c7.png)

And the overlay doesn't disappear. Never.

**Comment by vivekdtiwari** [comment]
@krrishh-org 
The command is literally 'toggle'. Pressing it once makes the modal come up and again makes the modal go. Silly to even have this though hence removing the option `Ctrl + Alt + O` in next patch. Will add any relevant shortcut we need later.

**Comment by vivekdtiwari** [comment]
@krrishh-org put out a minor patch that auto-closes the modal now. Will remove shortcut in soon
